theme: plainwhite
remote_theme: samarsault/plainwhite-jekyll
plainwhite:
  name: CaoZhi
  tagline: Developer. Designer
  date_format: "%b %-d, %Y"

  social_links:
    wechat: ImCaoZhi
    github: csmaile
    linkedIn: in/samarsault # format: locale/username
  portfolio_image:      "assets/portfolio.png"
  portfolio_image_dark: "assets/portfolio_dark.png"
  disqus_shortname: games
  sitemap: true
  navigation:
    - title: My Work
      url: "/my-work"
    - title: Resume
      url: "/resume"
  condensed_mobile:
    - home
    - post
    - page
  search: true
  html_lang: "en"
show_excerpts: true
baseurl: "/blog"


